# Introduction on how to use NumPy


In [3]:
import numpy as np

numpy.__version__

#reminder: you can use npa.<TAB> to see attributes of np(numpy)

'2.2.3'

# Understanding Data Types in Python

## A python integer is more than just an integer

every python object is simply a cleverly-disguised C structure which contains its value, and other information like the reference, type of variable, size of data.

```C
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};
```
ob_refcnt, a reference count that helps Python silently handle memory allocation and deallocation
ob_type, which encodes the type of the variable
ob_size, which specifies the size of the following data members
ob_digit, which contains the actual integer value that we expect the Python variable to represent.

In [5]:
# Fixed type arrays in python
import array,sys
L = list(range(10))
A = array.array('i', L)

print(A)

print(sys.getsizeof(L))
print(sys.getsizeof(A))

# Fixed type arrays are useful when you need to store a single type of data and consume less memory


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
136
120


# Creating arrays from python lists
we can use np.array to create arrays from python lists

In [4]:
import numpy as np
#integer array
np.array([1,2,3,4,5])
# if types dont match numpy will upcast if possible
# here integers are up-cast to float point:
np.array([3.14, 4, 2 , 3])
# explicity set data type of array
np.array([1,2,3,4], dtype='float32')
# numpy arrays can explicitly be multi-dimensional:
np.array([range(i, i + 3) for i in [2,4,6]])

# inner lists are treated as rows of rsulting two-dimensional array.



array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Creating Arrays from scratch
for large arrays is more efficient to create arrays from scratch using routines built into numpy:

In [21]:
# len 10 integer array filled with zeros
np.zeros(10, dtype=int)

# Create a 3x5 floating-point arrat filled with ones
np.ones((3,5), dtype=float)

# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

# array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)

# array of 5 values spaced between 0 and 1
np.linspace(0, 1, 5)

# 3x3 array of uniformly distrubuted
# random values between 0 and 1
np.random.random((3,3))
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))
# 3x3 array of random integers in the interval [0,10]
np.random.randint(0, 10, (3,3))
# 3x3 identity matrix
np.eye(3)
# uninitialized array of three integers
# values will be wathever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

# NumPy standard data types
numpy arrays contain values fo a single type.
numpy is built in C, types will be familiar to users of C,Fortran, etc.
Standard numpy data types are listed in the followed table.


Data type	Description
bool_	Boolean (True or False) stored as a byte
int_	Default integer type (same as C long; normally either int64 or int32)
intc	Identical to C int (normally int32 or int64)
intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8	Byte (-128 to 127)
int16	Integer (-32768 to 32767)
int32	Integer (-2147483648 to 2147483647)
int64	Integer (-9223372036854775808 to 9223372036854775807)
uint8	Unsigned integer (0 to 255)
uint16	Unsigned integer (0 to 65535)
uint32	Unsigned integer (0 to 4294967295)
uint64	Unsigned integer (0 to 18446744073709551615)
float_	Shorthand for float64.
float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_	Shorthand for complex128.
complex64	Complex number, represented by two 32-bit floats
complex128	Complex number, represented by two 64-bit floats

In [24]:
# Example
np.zeros(10, dtype='int16')
# using associated numpy object
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

# Numpy array attributes
We will talk about three randome arrays, one dimensional, two dimensional and three dimensional arrays,  we'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code runs:

In [63]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # one dimensional
x2 = np.random.randint(10, size=(3,4)) # Two dimensional
x3 = np.random.randint(10, size=(3, 4, 5)) # three dimensional
print(x1)
print(x2)
print(x3)
# each array has attributes ndim(number of dimensions)
# shape (the size of each dimension)
# size (total size of the array)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [68]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

# dtype: data type of array
print("dtype: ", x3.dtype)

#itemsize lists size in bytes of each array
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

# nbytes is equal to itemsize times size.


x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:  int64
itemsize:  8 bytes
nbytes:  480 bytes


# Array indexing: accessing single elements
numpy feels similar to python standard list indexing, a value can be accessed by specifying the desired index in square brackets:

In [79]:
x1
x1[0]
x1[4]
# index from the end of the array
x1[-1]
x1[-2]


np.int64(7)

In [80]:
# in multi dimensional arrays
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [81]:
x2[0,0]

np.int64(3)

In [82]:
x2[2,0]

np.int64(1)

In [83]:
x2[2,-1]

np.int64(7)

# Array slicing: accessing subarrays
numpy slicing syntax follows that of the standard python list; to access a slice of an array x, use this:

x[start:stop:step]


## one dimensional subarrays

In [84]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [86]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [87]:
x[4:7] # middle sub-array

array([4, 5, 6])

In [88]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [92]:
x[1::2] # every other element starting at index 1

array([1, 3, 5, 7, 9])

# Multi dimensional subarrays
work in the same way with multiple slices separated by commas.

In [93]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [94]:
x2[:2, :3] # all rows, every other column

array([[3, 5, 2],
       [7, 6, 8]])

In [95]:
# reversed
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [99]:
# accesing array rows and columns

print(x2[:, 0]) #first column of x2
print(x2[0,:])  #first row of x2


[3 7 1]
[3 5 2 4]


## Subarrays as no copy views
is important to know that arrays slices are views and not copies of the array data, here numpy differs from python list slicing, in lists, slices will be copies.

In [100]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [101]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


now if we modify thes subarray we'll see that the original array is changed:

In [102]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [103]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


sometimes can be useful to have a explicitly copy of the data, this can be done with copy() method:

In [104]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


## Reshaping of arrays
Anotther useful type of operation is reshaping of arrays.
this operation can be done with reshape method.

If you want to put the numbers 1 through 9 in a 3 x 3 grid, you can do the following:

In [114]:
grid = np.arange(1,10)
print(grid)
grid_reshaped = grid.reshape(3,3)
print('\n', grid_reshaped)

[1 2 3 4 5 6 7 8 9]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


the shape of the initial array must match the size of the reshaped array.

another common reshaping pattern is the conversion of a one dimensional array into a two dimensional row or column matrix.

In [115]:
x = np.array([1,2,3])
# row vector via reshape
x.reshape((1,3))


array([[1, 2, 3]])